---
- name: install python3-docker
  hosts: all
  tasks:
  - apt:
       name: python3-docker
       state: latest
       update_cache: yes
- name: Deploy Watchtower
  hosts: all
  become: yes
  tasks:
  - community.docker.docker_container:
       name: watchtower
       image: containrrr/watchtower
       volumes:
        - /var/run/docker.sock:/var/run/docker.sock
       restart_policy: always
