---
# installs python3 so the community.docker.docker_container module can run
- name: install python3-docker
  hosts: all
  tasks:
  - apt:
       name: python3-docker
       state: present
# deploys watchtower container to auto update docker containers
- name: Deploy Watchtower
  hosts: all
  become: yes
  tasks:
  - community.docker.docker_container:
       name: watchtower
       image: containrrr/watchtower
       #schedule to run every monday @ 11pm
       command: --schedule "00 23 ? * MON *"
       volumes:
        - /var/run/docker.sock:/var/run/docker.sock
       restart_policy: always
