---
- name: Create and configure Proxmox LXC container
  hosts: all
  gather_facts: false
  tasks:
    - name: Create LXC container
      community.proxmox.proxmox:
        api_host: 192.168.200.247
        api_user: ansible@pam # Use root@pam or the user with API privileges
        #api_password: 
        api_token_id: ansible-token
        api_token_secret: 0b529683-982e-4efa-a230-6989c2758e91 # Reference secret from Semaphore keystore
        vmid: 301 # change to whatever vmid you want
        node: pve
        hostname: test
        password: zaq1ZAQ! # Initial password for the container's root user
        ostemplate: 'ProxmoxStorage:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst'
        pubkey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHO1MyeuXcr0wzaXE/2qe5PUsoqItRQOderUGZFAqzrR root@semaphore'
        storage: local-lvm
        cores: 2
        memory: 512
        netif:
          net0: "name=eth0,ip=192.168.200.12/24,gw=192.168.200.1,bridge=vmbr0"
        state: present
      #delegate_to: localhost
    - name: start container
      community.proxmox.proxmox:
        vmid: 301
        api_host: 192.168.200.247
        api_user: ansible@pam
        api_token_id: ansible-token
        api_token_secret: 0b529683-982e-4efa-a230-6989c2758e91
        state: started
    #- name: enter container and modify ssh
      #ansible.builtin.shell:
        #pct enter 301 &&
        #cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak #&&
        #echo "PermitRootLogin yes" >> /etc/ssh/sshd_config &&
        #echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config  
