---
- hosts: all
  become: true

  tasks:
    - name: update repository cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install Proxmoxer
      apt:
        name:
          - python3-proxmoxer
        state: latest
