---
- name: Prune unused docker images
  hosts: docker
  tasks:
    - name: Run prune command
      shell: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once
