---
- name: TEST Create and configure Proxmox LXC container
  hosts: all
  gather_facts: false
  tasks:
    - name: Create LXC container
      community.proxmox.proxmox:
        api_host: 192.168.200.247
        api_user: ansible@pam # Use root@pam or the user with API privileges
        #api_password: 
        api_token_id: ansible-token
        api_token_secret: 0b529683-982e-4efa-a230-6989c2758e91 # Reference secret from Semaphore keystore
        vmid: 301
        node: pve
        hostname: test
        password: zaq1ZAQ! # Initial password for the container's root user
        ostemplate: 'local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst'
        storage: local-lvm
        #cores: 2
        #memory: 512
        #netif:
         # net0: "name=eth0,ip=192.168.200.12/24,gw=192.168.200.1,bridge=vmbr0"
        state: present
      #delegate_to: localhost
