---
- name: TEST Create and configure Proxmox LXC container
  hosts: all
  gather_facts: false
  tasks:
    - name: Create LXC container
      community.proxmox.proxmox:
        api_host: "{{ ansible_host }}"
        api_user: root@pam # Use root@pam or the user with API privileges
        #api_token_id: your_token_id
        #api_token_secret: "{{ proxmox_api_token_secret }}" # Reference secret from Semaphore keystore
        vmid: 301
        node: pve
        hostname: test
        password:  SkarmBliss!808 # Initial password for the container's root user
        ostemplate: /mnt/user/Proxmox/debian-13-standard_13.1-2_amd64.tar.zst
        storage: local-lvm
        cores: 2
        memory: 512
        netif:
          net0: "name=eth0,ip=192.168.200.12/24,gw=192.168.200.1,bridge=vmbr0"
        state: present
      #delegate_to: localhost
