---
- name: update LXC containers
  hosts: all
  tasks:
  - apt:
       name: "*"
       state: latest
       update_cache: yes
       allow_releaseinfo_change: yes
       autoclean: yes
       autoremove: yes
       autoclean: yes
