---
- name: Allow release info change
  lineinfile:
      path: /etc/apt/apt.conf.d/99releaseinfochange
      state: present
      create: yes
      line: Acquire::AllowReleaseInfoChange::Suite "true";
- name: update LXC containers
  hosts: all
  tasks:
  - apt:
       name: "*"
       state: latest
       update_cache: yes
