---
- name: update authentik
  hosts: authentik
  
  tasks:
  - name: update lxc container
    apt:
       name: "*"
       state: latest
       update_cache: yes
       autoclean: yes
       autoremove: yes
