---
- name: update authentik
  hosts: authentik
  
  tasks:
  - name: update lxc container
    apt:
       name: "*"
       state: latest
       update_cache: yes
       autoclean: yes
       autoremove: yes
  
  - name: upgrade authentik
    ansible.builtin.shell:
      mv docker-compose.yml docker-compose.yml.bk &&
      wget -O docker-compose.yml https://docs.goauthentik.io/docker-compose.yml &&
      docker compose pull &&
      docker compose up -d

  - name: prune unused docker images
    ansible.builtin.shell: docker image prune -af
