---
- name: update authentik
  hosts: authentik
  
  tasks:
  - name: backup current docker-compose.yml
    ansible.builtin.shell:
      mv docker-compose.yml docker-compose.yml.bk
  
  - name: grab newest docker-compose.yml
    ansible.builtin.shell:
      wget -O docker-compose.yml https://docs.goauthentik.io/docker-compose.yml

  - name: docker compose pull
    ansible.builtin.shell:
      docker compose pull

  - name: docker compose up
    ansible.builtin.shell:
      docker compose up -d

  - name: prune unused docker images
    ansible.builtin.shell: docker image prune -af

# upgrade breaks when updating the lxc container
  #- name: update lxc container
  #  apt:
  #     name: "*"
  #     state: latest
  #     update_cache: yes
  #     autoclean: yes
  #     autoremove: yes
