---
- name: update authentik
  hosts: authentik
  
  tasks:
  - name: update lxc container
    apt:
       name: "*"
       state: latest
       update_cache: yes
       autoclean: yes
       autoremove: yes
  
  - name: upgrade authentik
    ansible.builtin.shell:
      mv docker-compose.yml docker-compose.yml.bk
