---
- name: update ansible/semaphore
  hosts: all
  tasks:
   - name: update ansible/semaphore
     ansible.builtin.shell: |
      apt-get update &&
      apt-get upgrade -y &&
      apt-get clean &&
      python3 -m pip install --upgrade pip &&
      python3 -m pip install --upgrade --user ansible &&
      bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/ct/semaphore.sh)"
